# Generated by Django 4.2 on 2025-06-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("area", models.CharField(blank=True, max_length=100)),
                ("property_type", models.CharField(blank=True, max_length=50)),
                ("bedrooms", models.PositiveIntegerField(blank=True, null=True)),
                ("bathrooms", models.PositiveIntegerField(blank=True, null=True)),
                ("min_price", models.PositiveIntegerField(blank=True, null=True)),
                ("max_price", models.PositiveIntegerField(blank=True, null=True)),
                ("min_size", models.PositiveIntegerField(blank=True, null=True)),
                ("max_size", models.PositiveIntegerField(blank=True, null=True)),
                ("furnished", models.BooleanField(default=False)),
            ],
        ),
    ]