# Generated by Django 5.2.2 on 2025-06-09 11:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid.', max_digits=10)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of the payment.')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], default='credit_card', help_text='Method used for payment.', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Optional: Transaction ID from payment gateway.', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of the payment.', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about the payment.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(help_text='The broker who made the payment.', limit_choices_to={'user_type': 'broker'}, on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='inquiries.userprofile')),
            ],
            options={
                'verbose_name': 'Payment Log',
                'verbose_name_plural': 'Payment Logs',
                'ordering': ['-payment_date'],
            },
        ),
    ]
