# Generated by Django 5.2.2 on 2025-06-10 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_paymentlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(help_text='Name of the broker who accepted the inquiry', max_length=100)),
                ('commission', models.DecimalField(decimal_places=2, help_text='Commission percentage (0.00 to 100.00)', max_digits=5)),
                ('notes', models.TextField(blank=True, help_text='Additional notes from the broker')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inquiry', models.OneToOneField(help_text='The inquiry that was accepted', on_delete=django.db.models.deletion.CASCADE, related_name='broker_post', to='inquiries.inquiry')),
            ],
            options={
                'verbose_name': 'Broker Post',
                'verbose_name_plural': 'Broker Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
