# Generated by Django 5.2.1 on 2025-06-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_inquiry_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('user', 'User'), ('broker', 'Broker')], default='user', max_length=10)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('national_id', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('license_image', models.ImageField(blank=True, null=True, upload_to='licenses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
