# Generated by Django 5.2.2 on 2025-06-10 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_brokerpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale')], help_text='Whether this property is for rent or sale', max_length=10)),
                ('city', models.CharField(help_text='City/Governorate', max_length=50)),
                ('area', models.CharField(help_text='Specific area within the city', max_length=100)),
                ('property_type', models.CharField(choices=[('Roof', 'Roof'), ('Apartment', 'Apartment'), ('Duplex', 'Duplex'), ('Villa', 'Villa')], help_text='Type of property', max_length=20)),
                ('bedrooms', models.PositiveIntegerField(help_text='Number of bedrooms')),
                ('bathrooms', models.PositiveIntegerField(help_text='Number of bathrooms')),
                ('size', models.PositiveIntegerField(help_text='Size in square meters')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in EGP', max_digits=12)),
                ('furnished', models.CharField(choices=[('Furnished', 'Furnished'), ('Not-Furnished', 'Not Furnished')], help_text='Furnished status', max_length=20)),
                ('finish', models.CharField(blank=True, choices=[('Finished', 'Finished'), ('Unfinished', 'Unfinished'), ('Semi-Finished', 'Semi-Finished')], help_text='Finish status (for sale properties)', max_length=20, null=True)),
                ('media_files', models.JSONField(blank=True, default=list, help_text='List of uploaded media file paths')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this property listing is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(help_text='The broker who listed this property', limit_choices_to={'user_type': 'broker'}, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='inquiries.userprofile')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
