# Generated by Django 5.2.3 on 2025-06-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0004_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerpost',
            name='broker_phone',
            field=models.CharField(default='+20 000 000 0000', help_text='Phone number of the broker who accepted the inquiry', max_length=15),
        ),
    ]
