# Generated by Django 5.2.2 on 2025-06-11 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0005_brokerpost_broker_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(help_text='Unique broker registration number', max_length=20, unique=True)),
                ('registration_date', models.DateField(help_text='Date when broker was registered')),
                ('license_expiry', models.DateField(blank=True, help_text='License expiry date', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the registration is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.OneToOneField(help_text='The broker this registration belongs to', limit_choices_to={'user_type': 'broker'}, on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='inquiries.userprofile')),
            ],
            options={
                'verbose_name': 'Broker Registration',
                'verbose_name_plural': 'Broker Registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrokerRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_notes', models.TextField(blank=True, help_text="Customer's reason for rejection")),
                ('notified', models.BooleanField(default=False, help_text='Whether broker has been notified of rejection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker_post', models.OneToOneField(help_text='The broker post that was rejected', on_delete=django.db.models.deletion.CASCADE, related_name='rejection', to='inquiries.brokerpost')),
            ],
            options={
                'verbose_name': 'Broker Rejection',
                'verbose_name_plural': 'Broker Rejections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_notes', models.TextField(blank=True, help_text="Customer's notes when accepting the deal")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('interview_pending', 'Interview Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the deal', max_length=20)),
                ('broker_rating', models.PositiveIntegerField(blank=True, help_text='Customer rating for broker (1-5 stars)', null=True)),
                ('rating_notes', models.TextField(blank=True, help_text="Customer's notes about the broker rating")),
                ('commission_paid', models.BooleanField(default=False, help_text='Whether commission has been paid')),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Actual commission amount paid', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview_scheduled_at', models.DateTimeField(blank=True, help_text='When the interview review is scheduled', null=True)),
                ('broker_post', models.OneToOneField(help_text='The broker post that was accepted', on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='inquiries.brokerpost')),
                ('inquiry', models.OneToOneField(help_text='The inquiry that was accepted by customer', on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='inquiries.inquiry')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'ordering': ['-created_at'],
            },
        ),
    ]
