# Generated by Django 5.2.3 on 2025-06-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0006_brokerregistration_brokerrejection_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerpost',
            name='media',
            field=models.JSONField(blank=True, default=list, help_text='List of uploaded media file paths'),
        ),
    ]
