# Generated by Django 5.2.2 on 2025-06-05 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveIntegerField()),
                ("location", models.CharField(max_length=200)),
                ("property_type", models.CharField(max_length=50)),
                ("size", models.PositiveIntegerField()),
                ("bathrooms", models.PositiveIntegerField()),
                ("bedrooms", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="inquiries.inquiry",
                    ),
                ),
            ],
        ),
    ]
